import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import React from "react";
import RootNavbar from "@/components/RootNavbar";
import DefaultNavbar from "@/components/defaultNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const RootLayout = ({ children }) => {
  return (
    <div className="flex justify-center">
      <div className="w-full md:w-[680px] sm:px-10 px-5 py-[5px]">
        <RootNavbar />
        {children}
      </div>
    </div>
  );
};

const DefaultLayout = ({ children }) => {
  return (
    <div className="flex justify-center">
      <div className="w-full md:w-[680px] sm:px-10 px-5 py-[5px]">
        <DefaultNavbar />
        {children}
      </div>
    </div>
  );
};

 const DynamicLayout = ({ children }) => {
  const router = useRouter();
  const isRootPath = router.pathname === "/";

  return isRootPath ? (
    <RootLayout>{children}</RootLayout>
  ) : (
    <DefaultLayout>{children}</DefaultLayout>
  );
};


export default DynamicLayout